### PR TITLE
Add umd builds for react-fela

### PR DESCRIPTION
**Pull request by IgorBabkin**
```javascript
cd packages/react-fela && yarn build:umd
```

### CODE REVIEW

**Comment by robinweser** [comment]
Would you be open to introduce that change for every package? Should be easy to do that with Lerna. Externals should be `React`, `Preact` and `Inferno` as of today.

Would love to have that =) 
Thanks for your PR anyways!

**Comment by IgorBabkin** [comment]
I've introduced common solution how to simply add UMD bundling for any package. And also have added bundling for packages I need in my projects. I think we need to add UMD on demand. Some of package no need UMD because they are lightweight like `fela-plugin-fallback` or `fela-unit`.

**Comment by IgorBabkin** [comment]
Let me know for what packages you want to have UMD?

**Comment by IgorBabkin** [comment]
@robinweser Should I add anything?

**Comment by robinweser** [comment]
Hey Igor,
It looks fine for now. I might refactor it later to an external script just like the build script with a single reused webpack config if possible. So we don't have to add it to each package, but rather build from the root, but I'll merge it now to release the changes :)

**Pull request merged**
